baseURL: "https://zararsiddiqi.com/"
languageCode: "en-us"
title: "Zarar Siddiqi's blog"
theme: "hugo-theme-anubis"
paginate: "10000"
enableInlineShortcodes: true
enableRobotsTXT: true
permalinks:
  posts: "/:filename/"
minify:
    disableXML: true
    minifyOutput: true

languages:
  en:
    languageName: "English"
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Me
          url: pages/me

params:
  defaultTheme: auto
  ShowShareButtons: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowRssButtonInSectionTermList: true
  profileMode:
    enabled: true
  socialIcons:
    - name: "Twitter"
      url: "https://twitter.com/zararsiddiqi"

outputs:
    home:
        - HTML
        - RSS
        - JSON
markup:
    goldmark:
        renderer:
            unsafe: true